# Generated by Django 6.0.3 on 2026-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('artist', 'Artista'), ('group_admin', 'Administrador de Agrupación')], default='artist', max_length=20),
        ),
    ]
