# Generated by Django 6.0.3 on 2026-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_linea'),
        ('groups', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_groups', to='artists.artist'),
        ),
    ]
