# Generated by Django 6.0.3 on 2026-04-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artistimage'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='catalog.lineaartistica'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
