# Generated by Django 6.0.3 on 2026-04-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_linea_alter_artist_description_and_more'),
        ('groups', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='groups.group'),
        ),
    ]
