# Generated by Django 6.0.3 on 2026-04-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_group'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.lineaartistica'),
        ),
    ]
